.github/workflows/hassfest.yml, .github/workflows/publish.yml, .github/workflows/validate.yml, custom_components/dimo/manifest.json, hacs.json
=> Hacs readiness

custom_components/dimo/dimoapi/auth.py, tests/test_auth.py
instead of relying on a hardcoded 10 minute expiration, we parse the jwt and retrieve the expiration timestamp from the token directly.
Fixes #52
References #45
=> refactor(dimoapi): parse token expiry from jwt.

custom_components/dimo/manifest.json, requirements_test.txt
Use the fork by @msp1974 that removes the need for pydantic. Home Assistant core has now finally merged a PR that updates `pydantic` but this won't be available to users until 2015.1 release, so we can use the fork until then.
References #64
=> deps: bump dimo sdk to v0.0.7

custom_components/dimo/const.py
the number of total vehicles on DIMO can (unfortunately), go down, so we shouldn't use a state class that presumes the count always goes up.
Fixes #80
=> fix: corrected state class for total dimo vehicles sensor.

custom_components/dimo/__init__.py
by utilizing concurrency we can speed up the process of initializing DIMO vehicle devices. We use asyncio to retrieve available signals for the vehicles before we subsequently create associated Home Assistant devices.
=> refactor: retrieve initial available signals for vehicles concurrently.

custom_components/dimo/dimoapi/auth.py, custom_components/dimo/dimoapi/dimo_client.py, custom_components/dimo/manifest.json, requirements_test.txt
In a Home Assistant integration, it’s more typical to rely on the built-in logging library. This ensures consistent formatting, log levels, and it cooperates with Home Assistant’s logging system.
Using a single logger across your integration is cleaner, and Home Assistant dev guidelines also advise against mixing multiple logging libraries.
=> refactor: replaced loguru with standard logging.

custom_components/dimo/dimoapi/auth.py, custom_components/dimo/dimoapi/dimo_client.py, tests/test_auth.py, tests/test_dimo_client.py
no need to store the entire json response (for now). it creates pointless confusion.
=> refactor: store only the privileged token string.

custom_components/dimo/__init__.py, custom_components/dimo/dimoapi/auth.py, custom_components/dimo/dimoapi/dimo_client.py, tests/test_auth.py, tests/test_dimo_client.py
access tokens and privileged tokens are both JWT tokens and can hence be handled in the same way, including evaluating token expiration.
=> refactor: unify access token management

custom_components/dimo/dimoapi/auth.py, custom_components/dimo/dimoapi/dimo_client.py, requirements_test.txt, tests/test_dimo_client.py
This commit adds a simple wrapper around the DIMO SDK's vin retrieval helper method.
Since the DIMO mobile app currently doesnt support the ability to grant the necessary permissions for this API call to function, we will hold off on further implementation of VIN retrieval for now and revisit this later.
References #7
=> feat: added underlying VIN retrieval support.

custom_components/dimo/dimoapi/auth.py, custom_components/dimo/dimoapi/dimo_client.py, tests/helper.py, tests/test_auth.py, tests/test_dimo_client.py
handle the privileged token as AuthToken objects the same way we handle the access token
=> refactor: simplify and streamline privileged token parsing.

custom_components/dimo/base_entity.py
Using `_attr_` attributes instead of property methods is slightly more efficient, since attributes are assigned once rather than computed for every propery access. It also keeps the code cleaner and more consistent with the HA code style.
=> refactor: use _attr_ class attributes for DimoBaseEntity.

custom_components/dimo/config_flow.py
It is best practice to derive from Exception or HomeAssistantError so that it is caught by general exception handlers.
=> refactor: inherit from HomeAssistantError

custom_components/dimo/__init__.py, custom_components/dimo/base_entity.py, custom_components/dimo/dimoapi/auth.py, custom_components/dimo/dimoapi/dimo_client.py, custom_components/dimo/dimoapi/queries.py, tests/test_auth.py, tests/test_base_entity.py, tests/test_dimo_client.py, tests/test_init.py
Since the VIN uniquely identifies the vehicle and never changes, it makes sense to include it as an identifier in the device info for a given vehicle.
Fixes #7
Fixes #126
=> feat: added vehicle vin to device registry entry

custom_components/dimo/dimoapi/dimo_client.py
apparently, its possible for vehicles to lack any available signals. Hence we need to consider that before retrieving signal data.
Fixes #132
=> refactor: account for absence of signal data

custom_components/dimo/__init__.py
When transient errors occur, the methods log a warning and return without updating data, allowing the previously known good state to persist (and automations or history to remain unaffected).
Fixes #137
=> refactor: gracefully handle transient exceptions.

custom_components/dimo/dimoapi/auth.py
to account for potential clock drift between client and server we add a 60 second leeway.
=> refactor: add 60 seconds leeway to jwt expiration check

custom_components/dimo/dimoapi/dimo_client.py
when retrieving a new privileged access token we now check if the access token is still valid and refresh it if necessary.
Fixes #146
=> refactor: assert DIMO access token validity and refresh as required.

custom_components/dimo/sensor.py
Instead of directly indexing dictionaries we assert data existence before accessing the value.
References #153
=> refactor: be more defensive when parsing out sensor native value

custom_components/dimo/dimoapi/auth.py, custom_components/dimo/dimoapi/dimo_client.py, custom_components/dimo/manifest.json, requirements_test.txt, tests/test_auth.py, tests/test_dimo_client.py
The new version of the DIMO SDK v.1.3.0 includes privilege level retrieval so we can remove this mechanism from the integration code. There are also some renaming of methods, etc. 
Fixes #157
=> refactor: updated to Dimo SDK v1.3.0 and removed privilege retrieval

custom_components/dimo/dimoapi/dimo_client.py, custom_components/dimo/dimoapi/queries.py, tests/test_dimo_client.py
The DIMO SDK now contains a helper method to retrieve available signals for a given `token_id`, which is implements the exact same query as this integration does. We can therefore do a drop-in replacement, saving us some lines of code and potential maintenance load down the road.
=> refactor(dimoapi): migrate to new SDK available_signals method

custom_components/dimo/__init__.py, tests/test_init.py
the latest DIMO SDK introduces a new unified exception class (HTTPError) which removes the need for handling the numerous `requests` specific exceptions
=> refactor: replaced connection error exceptions with unified exception

custom_components/dimo/binary_sensor.py, tests/test_binary_sensor.py
makes sure we never call ``.get()`` on None and instead bubble up None to Home Assistant, which it interprets as “unavailable”.
Fixes #182
=> refactor: make DimoVehicleBinarySensorEntity guard against None entries.

custom_components/dimo/manifest.json, requirements_test.txt
The DIMO Python SDK was recently updated with more robust, but stricted response checks in order to
provide correctly decoded response data.
This worked fine at the time when v0.7.0 of the HA integration was published, but yesterday the DIMO API was updated and now requests return a different content type.
This caused returned data to not be json decoded which is what broke the Home Assistant integration
The DIMO Python SDK has now been updated with a refactored content type check.
Fixes #185
=> fix: updated dimo sdk for content-type checking fix

custom_components/dimo/dimoapi/auth.py, tests/test_auth.py
this elimitates duplicate token expiration checks and streamlines the mechanism for verifying token expiration
=> refactor: centralize and refine token expiration checks.

custom_components/dimo/dimoapi/auth.py
we shouldnt assume that a `token` value is always included in the response and handle its absence properly.
=> fix: assert that a token is actually returned during exchange.

custom_components/dimo/__init__.py, custom_components/dimo/dimoapi/dimo_client.py, tests/test_dimo_client.py
DIMO has recently intoduced a (conservative) complexity limit for Graphql queries. For vehicles with a large number of signals we end up exceeding this limit when we query for the values of all signals.
To work around this issue we can chunk up the queries and merge the responses in order to get all signal values
Fixes #199
=> refactor: implemented chunked signals retrieval

custom_components/dimo/__init__.py
temporary workaround hack to deal with the upstream DIMO api bug where currentLocationCoordinates, a signal provided by `getAvailableSignals`, results in the `signalLatest` query returning a 422 error.
Fixes #216
=> fix: remove incompatible signal from telemetry query
