- custom_components/dimo/dimoapi/dimo_client.py
> feat(dimoapi): added support for door lock/unlock commands

- custom_components/dimo/__init__.py
- custom_components/dimo/base_entity.py
- custom_components/dimo/binary_sensor.py
- custom_components/dimo/const.py
- custom_components/dimo/device_tracker.py
- custom_components/dimo/diagnostics.py
- custom_components/dimo/dimoapi/dimo_client.py
- custom_components/dimo/sensor.py
> feat: implemented DIMO-level sensor support

- custom_components/dimo/dimoapi/auth.py
added method docs and some return value types
> refactor: minor refactoring of auth.

- custom_components/dimo/dimoapi/auth.py
- custom_components/dimo/dimoapi/dimo_client.py
this commit removes some of the most frequent debug logging. We don't want to flood the HA logs and in the near future I'll remove all debug logging.
> refactor: removed noisy debug logging

- custom_components/dimo/const.py
> feat: added sensor definitions standard for Teslas.

- custom_components/dimo/__init__.py
retrieve signals for multiple vehicles concurrently with asyncio for improved performance.
> refactor: retrieve signal data with concurrency

- custom_components/dimo/__init__.py
Improve performance by having the coordinator updating both the DIMO sensor data and the vehicle signals concurrently, rather than doing DIMO sensors first and vehicles second.
> refactor: fetch DIMO sensor data in parallel.

- README.md
Updated README with refactored instructions thanks to DIMO licenses now being free for personal use.
> refactor: Updated README.

- custom_components/dimo/dimoapi/auth.py
- tests/test_auth.py
DIMO API access tokens currently expire after 14 days. This commit implements expiration checks and renewals as needed in order to maintain a valid access token.
Fixes #95
> refactor: manage access token expiration

- custom_components/dimo/dimoapi/dimo_client.py
minor refactor with improved exception handling, docstring and typing.
> refactor: cleaned up and improved get_total_dimo_vehicles.

- custom_components/dimo/device_tracker.py
- added source type
- added altitude attribute
- minor code cleanup
> refactor: improved the device tracker.

- custom_components/dimo/base_entity.py
The _signal property consolidates the dictionary lookup and avoids repeated lookups and calls to `get`.
> refactor: refined DimoBaseVehicleEntity

- custom_components/dimo/const.py
sensor return the list of trouble codes reported by the hardware device
> refactor: added DTC list sensor definition

- custom_components/dimo/device_tracker.py
> refactor: ensure geo data is available before adding device tracker

- custom_components/dimo/__init__.py
- custom_components/dimo/dimoapi/dimo_client.py
> refactor: catch requests ConnectionError instead of built in.

- README.md
Tweaked for increased clarity.
Fixes #160
> docs: refactured README.

- requirements_test.txt
- setup.cfg
- tests/test_config_flow.py
finally figured out the required fixtures and setup for config flow tests to be successfully run
> test: added unit tests for the config flow.

- custom_components/dimo/__init__.py
> refactor: catch http errors and handle them gracefully

- custom_components/dimo/dimoapi/dimo_client.py
> refactor: handle connection errors when retrieving vehicle vin.

- custom_components/dimo/base_entity.py
used to show device topology in Home Assistant.
> refactor: added via_device attribute

- custom_components/dimo/dimoapi/auth.py
- custom_components/dimo/manifest.json
- requirements_test.txt
by providing our custom requests session we get a retry strategy that can account for periodic API server issues
> refactor: added custom session and use forked DIMO SDK

- custom_components/dimo/dimoapi/dimo_client.py
> refactor: remove redudnant None fallbacks.

- custom_components/dimo/helpers.py
- tests/test_auth.py
- tests/test_helpers.py
slightly refactored the get_key helper method.
- Improved logging
- check isinstance to void TypeErrors.
> refactor: reworked get_key helper method. added tests.

- custom_components/dimo/const.py
this commit adds sensor definitions for window open state signals
> refactor: added window open signal sensors

- custom_components/dimo/const.py
> fix: added sensor state class for odometer sensor
